name: SFTP File Transfer

on:
  workflow_dispatch:
    inputs:
      origen_ip:
        description: 'IP del servidor origen (X)'
        required: true
      destino_ip:
        description: 'IP del servidor destino (Y)'
        required: true
      ruta_origen:
        description: 'Ruta en el servidor origen'
        required: true
      ruta_destino:
        description: 'Ruta en el servidor destino'
        required: true

jobs:
  transfer_files:
    runs-on: ubuntu-latest

    steps:
    - name: Instalar sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Descargar archivos desde servidor origen (X)
      run: |
        mkdir -p transfer-temp
        sshpass -p "${{ secrets.ORIGEN_PASS }}" sftp -oStrictHostKeyChecking=no -b - ${{ secrets.ORIGEN_USER }}@${{ github.event.inputs.origen_ip }} <<EOF
        get -r ${{ github.event.inputs.ruta_origen }} transfer-temp/
        bye
        EOF

    - name: Subir archivos a servidor destino (Y)
      run: |
        sshpass -p "${{ secrets.DESTINO_PASS }}" sftp -oStrictHostKeyChecking=no -b - ${{ secrets.DESTINO_USER }}@${{ github.event.inputs.destino_ip }} <<EOF
        put -r transfer-temp ${{ github.event.inputs.ruta_destino }}
        bye
        EOF

